displayName: Timestamp Header
type: middleware
import: github.com/helpshift/timestamp-injector
summary: "Adds timepstamp header with current time in seconds.milliseconds (like Nginx $msec)."
testData:
  Headers:
    HeadName: "mytimestamp"
